
// This file is automatically generated! Do not edit or modify this as it would be recreated.
import hillsAsset from '@client/assets/tilesets/fantasy-lands/hills.png';
import dummy_tileAsset from '@client/assets/tilesets/dummy-tile.png';
import ground_dec_propsAsset from '@client/assets/tilesets/fantasy-lands/ground_dec_props.png';
import decorations_mediumAsset from '@client/assets/tilesets/fantasy-lands/decorations_medium.png';
import treeAsset from '@client/assets/tilesets/fantasy-lands/Tree_A_v1.png';
import small_buildingsAsset from '@client/assets/tilesets/fantasy-lands/small_buildings.png';
import groundAsset from '@client/assets/tilesets/fantasy-lands/ground.png';
import water_envAsset from '@client/assets/tilesets/fantasy-lands/water_env.png';
import dummy_json_map from '@shared/maps/dummy/dummy.json?url';
import wooden_wallsAsset from '@client/assets/tilesets/fantasy-lands/interrior/Walls/FL_Houses_int_WallsD.png';
import floorsAsset from '@client/assets/tilesets/fantasy-lands/interrior/Floors/FL_Houses_int_Floors.png';
import internalsAsset from '@client/assets/tilesets/fantasy-lands/interrior/FL_Houses_int_sidesOfTheHouses.png';
import elementsAsset from '@client/assets/tilesets/fantasy-lands/interrior/FL_Houses_int_building elements.png';
import fire_placeAsset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/FL_Houses_int_FurnituresC.png';
import bedsTile0Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (1).png';
import bedsTile1Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (2).png';
import bedsTile2Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (3).png';
import bedsTile3Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (4).png';
import bedsTile4Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (5).png';
import bedsTile5Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (6).png';
import bedsTile6Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (7).png';
import bedsTile7Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (8).png';
import bedsTile8Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (9).png';
import bedsTile9Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (10).png';
import bedsTile10Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (11).png';
import bedsTile11Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (12).png';
import bedsTile12Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (13).png';
import bedsTile13Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (14).png';
import bedsTile14Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object (15).png';
import bedsTile15Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/beds/object.png';
import drobesTile0Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (1).png';
import drobesTile1Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (2).png';
import drobesTile2Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (3).png';
import drobesTile3Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (4).png';
import drobesTile4Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (5).png';
import drobesTile5Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (6).png';
import drobesTile6Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (7).png';
import drobesTile7Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (8).png';
import drobesTile8Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (9).png';
import drobesTile9Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object (25).png';
import drobesTile10Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/drobes/object.png';
import chairsTile0Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/chairs/object (5).png';
import chairsTile1Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/chairs/object (6).png';
import chairsTile2Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/chairs/object (7).png';
import chairsTile3Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/chairs/object (8).png';
import tablesTile0Asset from '@client/assets/tilesets/fantasy-lands/interrior/Furnitures/tables/object.png';
import dummy_house_json_map from '@shared/maps/dummy/dummy-house.json?url';
import tree_aAsset from '@client/assets/tilesets/fantasy-lands/Tree_A_v1.png';
import tree_bAsset from '@client/assets/tilesets/fantasy-lands/Tree_B_v1.png';
import interborder_json_map from '@shared/maps/interborder/interborder.json?url';

import { MapPackage } from '@client/utils/types';

export const map: Record<string, MapPackage> = {
  'dummy': {
      map: {
        key: 'dummy-tiled-map',
        asset: dummy_json_map
      },
      assets: [{
        key: 'hills',
        type: 'sprite',
        asset: hillsAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'dummy-tile',
        type: 'sprite',
        asset: dummy_tileAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'ground_dec_props',
        type: 'sprite',
        asset: ground_dec_propsAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'decorations_medium',
        type: 'sprite',
        asset: decorations_mediumAsset,
        config: {"frameWidth":64,"frameHeight":64}
        },{
        key: 'tree',
        type: 'sprite',
        asset: treeAsset,
        config: {"frameWidth":128,"frameHeight":128}
        },{
        key: 'small-buildings',
        type: 'sprite',
        asset: small_buildingsAsset,
        config: {"frameWidth":160,"frameHeight":192}
        },{
        key: 'ground',
        type: 'sprite',
        asset: groundAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'water_env',
        type: 'sprite',
        asset: water_envAsset,
        config: {"frameWidth":32,"frameHeight":32}
        }]
    },
'dummy-house': {
      map: {
        key: 'dummy-house-tiled-map',
        asset: dummy_house_json_map
      },
      assets: [{
        key: 'wooden_walls',
        type: 'sprite',
        asset: wooden_wallsAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'floors',
        type: 'sprite',
        asset: floorsAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'internals',
        type: 'sprite',
        asset: internalsAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'elements',
        type: 'sprite',
        asset: elementsAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'fire_place',
        type: 'sprite',
        asset: fire_placeAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'dummy-tile',
        type: 'sprite',
        asset: dummy_tileAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'beds',
        type: 'multiple',
        frames: [{
          id: 2,
          asset: bedsTile0Asset,
          config: {"frameWidth":64,"frameHeight":64}
          },{
          id: 3,
          asset: bedsTile1Asset,
          config: {"frameWidth":64,"frameHeight":64}
          },{
          id: 4,
          asset: bedsTile2Asset,
          config: {"frameWidth":64,"frameHeight":64}
          },{
          id: 5,
          asset: bedsTile3Asset,
          config: {"frameWidth":32,"frameHeight":96}
          },{
          id: 6,
          asset: bedsTile4Asset,
          config: {"frameWidth":32,"frameHeight":96}
          },{
          id: 7,
          asset: bedsTile5Asset,
          config: {"frameWidth":64,"frameHeight":96}
          },{
          id: 8,
          asset: bedsTile6Asset,
          config: {"frameWidth":32,"frameHeight":96}
          },{
          id: 9,
          asset: bedsTile7Asset,
          config: {"frameWidth":32,"frameHeight":96}
          },{
          id: 10,
          asset: bedsTile8Asset,
          config: {"frameWidth":64,"frameHeight":96}
          },{
          id: 11,
          asset: bedsTile9Asset,
          config: {"frameWidth":64,"frameHeight":96}
          },{
          id: 12,
          asset: bedsTile10Asset,
          config: {"frameWidth":32,"frameHeight":96}
          },{
          id: 13,
          asset: bedsTile11Asset,
          config: {"frameWidth":32,"frameHeight":96}
          },{
          id: 14,
          asset: bedsTile12Asset,
          config: {"frameWidth":64,"frameHeight":96}
          },{
          id: 15,
          asset: bedsTile13Asset,
          config: {"frameWidth":32,"frameHeight":96}
          },{
          id: 16,
          asset: bedsTile14Asset,
          config: {"frameWidth":32,"frameHeight":96}
          },{
          id: 17,
          asset: bedsTile15Asset,
          config: {"frameWidth":64,"frameHeight":64}
          }
        ]
        },{
        key: 'drobes',
        type: 'multiple',
        frames: [{
          id: 12,
          asset: drobesTile0Asset,
          config: {"frameWidth":42,"frameHeight":70}
          },{
          id: 13,
          asset: drobesTile1Asset,
          config: {"frameWidth":32,"frameHeight":32}
          },{
          id: 14,
          asset: drobesTile2Asset,
          config: {"frameWidth":32,"frameHeight":47}
          },{
          id: 15,
          asset: drobesTile3Asset,
          config: {"frameWidth":32,"frameHeight":30}
          },{
          id: 16,
          asset: drobesTile4Asset,
          config: {"frameWidth":24,"frameHeight":30}
          },{
          id: 17,
          asset: drobesTile5Asset,
          config: {"frameWidth":24,"frameHeight":30}
          },{
          id: 18,
          asset: drobesTile6Asset,
          config: {"frameWidth":50,"frameHeight":60}
          },{
          id: 19,
          asset: drobesTile7Asset,
          config: {"frameWidth":32,"frameHeight":67}
          },{
          id: 20,
          asset: drobesTile8Asset,
          config: {"frameWidth":32,"frameHeight":52}
          },{
          id: 36,
          asset: drobesTile9Asset,
          config: {"frameWidth":32,"frameHeight":67}
          },{
          id: 37,
          asset: drobesTile10Asset,
          config: {"frameWidth":32,"frameHeight":67}
          }
        ]
        },{
        key: 'chairs',
        type: 'multiple',
        frames: [{
          id: 5,
          asset: chairsTile0Asset,
          config: {"frameWidth":18,"frameHeight":34}
          },{
          id: 6,
          asset: chairsTile1Asset,
          config: {"frameWidth":18,"frameHeight":34}
          },{
          id: 7,
          asset: chairsTile2Asset,
          config: {"frameWidth":18,"frameHeight":33}
          },{
          id: 8,
          asset: chairsTile3Asset,
          config: {"frameWidth":18,"frameHeight":25}
          }
        ]
        },{
        key: 'tables',
        type: 'multiple',
        frames: [{
          id: 0,
          asset: tablesTile0Asset,
          config: {"frameWidth":42,"frameHeight":34}
          }
        ]
        }]
    },
'interborder': {
      map: {
        key: 'interborder-tiled-map',
        asset: interborder_json_map
      },
      assets: [{
        key: 'ground',
        type: 'sprite',
        asset: groundAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'hills',
        type: 'sprite',
        asset: hillsAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'tree_a',
        type: 'sprite',
        asset: tree_aAsset,
        config: {"frameWidth":128,"frameHeight":128}
        },{
        key: 'tree_b',
        type: 'sprite',
        asset: tree_bAsset,
        config: {"frameWidth":160,"frameHeight":176}
        },{
        key: 'ground_dec_props',
        type: 'sprite',
        asset: ground_dec_propsAsset,
        config: {"frameWidth":32,"frameHeight":32}
        },{
        key: 'decorations_medium',
        type: 'sprite',
        asset: decorations_mediumAsset,
        config: {"frameWidth":64,"frameHeight":64}
        },{
        key: 'water_env',
        type: 'sprite',
        asset: water_envAsset,
        config: {"frameWidth":32,"frameHeight":32}
        }]
    }
};

export const isMapBundleKey = (name: string): name is keyof typeof map => {
  return name in map;
};
