// This file is automatically generated! Do not edit or modify this as it would be recreated.
import base_spriteAsset from './aseprite/png/base-sprite.png';
import base_spriteJson from './aseprite/json/base-sprite.json?url';
import dummy_spriteAsset from './aseprite/png/dummy-sprite.png';
import dummy_spriteJson from './aseprite/json/dummy-sprite.json?url';
import pigAsset from './aseprite/png/pig.png';
import pigJson from './aseprite/json/pig.json?url'

export const map = {
  base: {
    asset: base_spriteAsset,
    json: base_spriteJson,
    type: 'aseprite',
  },
  dummy: {
    asset: dummy_spriteAsset,
    json: dummy_spriteJson,
    type: 'aseprite',
  },
  pig: {
    asset: pigAsset,
    json: pigJson,
    type: 'aseprite',
  },

} as const;

export const isAssetKey = (key: unknown): key is keyof typeof map => {
  return typeof key === 'string' && key in map;
};
