import fs from 'fs/promises';
import path from 'path';

const clientPath = path.resolve(process.cwd(), './src/client');

(async () => {
  try {
    const images = await fs.readdir(path.resolve(clientPath, './assets/sprites/aseprite/png'));
    const configs = await fs.readdir(path.resolve(clientPath, './assets/sprites/aseprite/json'));
    const assets: {
      [name: string]: {
        asset: string;
        json?: string;
        type: 'aseprite' | 'sprite';
      };
    } = {};
    const imports = [];
    const names = images
      .map((file) => file.split('.').slice(0, -1).join('.'))
      .reduce((acc, name) => {
        acc.add(name);

        return acc;
      }, new Set<string>());

    for (const name of names.keys()) {
      if (images.includes(`${name}.png`) && configs.includes(`${name}.json`)) {
        imports.push(`import ${name.replaceAll('-', '_')}Asset from './aseprite/png/${name}.png'`);
        imports.push(`import ${name.replaceAll('-', '_')}Json from './aseprite/json/${name}.json?url'`);
        assets[name] = {
          asset: `${name.replaceAll('-', '_')}Asset`,
          json: `${name.replaceAll('-', '_')}Json`,
          type: 'aseprite',
        };
      }
    }

    const template = `\/\/ This file is automatically generated! Do not edit or modify this as it would be recreated.
${imports.join(';\n')}

export const map = {
${Object.entries(assets).reduce((acc, [name, asset]) => {
  acc += `  ${name.split('-')[0]}: {
    asset: ${asset.asset},
    json: ${asset.json},
    type: '${asset.type}',
  },\n`;

  return acc;
}, '')}
} as const;

export const isAssetKey = (key: unknown): key is keyof typeof map => {
  return typeof key === 'string' && key in map;
};
`;

    await fs.writeFile(path.resolve(clientPath, './assets/sprites/map.ts'), template);

    console.log('Assets map was successfully written');
    process.exit(0);
  } catch (e) {
    console.warn(e);
    process.exit(1);
  }
})();
