import fs from 'node:fs';
import path from 'path';
import { assets as assetsURIs, maps } from '@shared/maps/mapping';
import { MapPackage, MultipleSpriteAsset } from '@client/utils/types';

const clientPath = path.resolve(process.cwd(), 'src/client');
const imports: Map<string, string> = new Map();
const packages: Map<string, MapPackage> = new Map();

for (let key in maps) {
  const map = maps[key];
  const tilesets = map.tilesets;
  const assets: MapPackage['assets'] = [];

  for (let set of tilesets) {
    if ('source' in set) {
      console.warn('Process map files with "inclide-external-tilesets" script first!');

      process.exit(1);
    }
    const isSingleImageTileset = !!set.image;

    if (isSingleImageTileset) {
      const asset = `@client/${path.relative(clientPath, path.resolve(clientPath, `./${set.image.split('client')[1]}`))}`;
      const assetImport = `import ${set.name.replaceAll('-', '_')}Asset from '${asset}';`;
      imports.set(set.name, assetImport);

      assets.push({
        key: set.name,
        asset: `${set.name.replaceAll('-', '_')}Asset`,
        type: 'sprite',
        config: {
          frameWidth: set.tilewidth,
          frameHeight: set.tileheight,
        },
      });
    } else {
      const asset: MultipleSpriteAsset = {
        key: set.name,
        type: 'multiple',
        frames: [],
      };
      for (let i = 0; i < set.tiles.length; i++) {
        const tile = set.tiles[i];
        if (tile.image) {
          const assetPath = `@client/${path.relative(clientPath, path.resolve(clientPath, `./${tile.image.split('client')[1]}`))}`;
          const assetImport = `import ${set.name.replaceAll('-', '_')}Tile${i}Asset from '${assetPath}';`;
          imports.set(`${set.name}Tile${i}`, assetImport);

          asset.frames.push({
            id: tile.id,
            asset: `${set.name.replaceAll('-', '_')}Tile${i}Asset`,
            config: {
              frameWidth: tile.imagewidth,
              frameHeight: tile.imageheight,
            },
          });
        }
      }
      assets.push(asset);
    }
  }

  packages.set(key, {
    map: {
      key: `${key}-tiled-map`,
      asset: `${key.replaceAll('-', '_')}_json_map`,
    },
    assets,
  });

  imports.set(
    `${key}_json_map`,
    `import ${key.replaceAll('-', '_')}_json_map from '${assetsURIs[key as keyof typeof assetsURIs]}';`,
  );
}

const template = `
\/\/ This file is automatically generated! Do not edit or modify this as it would be recreated.
${imports.values().toArray().join('\n')}

import { MapPackage } from '@client/utils/types';

export const map: Record<string, MapPackage> = {
  ${packages
    .entries()
    .map(
      ([key, pack]) => `'${key}': {
      map: {
        key: '${pack.map.key}',
        asset: ${pack.map.asset}
      },
      assets: [${pack.assets
        .map(
          (asset) => `{
        key: '${asset.key}',
        type: '${asset.type}',
        ${
          asset.type === 'sprite'
            ? `asset: ${asset.asset},
        config: ${JSON.stringify(asset.config)}`
            : `frames: [${asset.frames
                .map(
                  ({ id, asset, config }) => `{
          id: ${id},
          asset: ${asset},
          config: ${JSON.stringify(config)}
          }`,
                )
                .join(',')}
        ]`
        }
        }`,
        )
        .join(',')}]
    }`,
    )
    .toArray()
    .join(',\n')}
};

export const isMapBundleKey = (name: string): name is keyof typeof map => {
  return name in map;
}
`;

fs.writeFile(path.resolve(clientPath, './assets/tilesets/map.ts'), template, (error) => {
  if (error) {
    console.warn(error);
    return;
  }

  console.log('Package file was successfully written');
});
